Added an Editor with upload/saving functionalities
JBossOutreach/react-online-editor pull request #1
Opened 2019-12-03 02:36 UTC by davidli3100

This is kind of two tasks in one, so I would appreciated it if I could get credit for both. 

Used `react-ace` to create the editor, and a few libraries to implement saving/reading of files

2019-12-03 05:57 UTC, KeenWarrior commented
@davidli3100 sorry for the inconvenience but we needed to change based folder structure. can you please rebase your commits?

2019-12-04 07:45 UTC, anshumanv commented
Thanks for the massive amount of work on this, please rebase as per the current folder structure. Thanks!

2019-12-04 22:49 UTC, divyanshu-rawat reviewed
Looks good, but do resolve merge conflicts, and do rebase.

2019-12-04 22:51 UTC, davidli3100 commented
Alright, rebasing tonight

2019-12-04 23:09 UTC, divyanshu-rawat requested changes

2019-12-04 23:09 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
> +        console.log(file)
Please do not leave console statements in the code.

2019-12-04 23:09 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
> +            console.log(this.aceRef)
would be great if you remove this.

2019-12-04 23:09 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
> +        var fileName = file.name;
if filename is not getting changes, which I believe is not, then make it a `const`

2019-12-04 23:09 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
> +        var fileType = file.type;
same here.

2019-12-04 23:09 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
> +        console.log(this.state)
would be great, if you remove console statement.

2019-12-04 23:09 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
> +        var file = new File([this.aceRef.editor.getValue()], this.state.fileName, {type: this.state.fileType+";charset=utf-8"});
if it is not changing make it `const`.

2019-12-04 23:09 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
> +    // openModal = () => {
don"t leave comments.

2019-12-04 23:09 UTC, divyanshu-rawat commented on src/Components/toolbar/toolbar.css
> +    margin: 10px 20px
I think you missed semi-colon here.

2019-12-04 23:09 UTC, divyanshu-rawat commented on src/Views/editor.js
> +                {/* <Toolbar/> */}
what is this here?

2019-12-04 23:22 UTC, divyanshu-rawat requested changes

2019-12-04 23:22 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
>          var reader = new FileReader();
reader is not getting changed right? can you check if we can also make it a `const`

2019-12-04 23:22 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
>          var file = new File([this.aceRef.editor.getValue()], this.state.fileName, {type: this.state.fileType+";charset=utf-8"});
It is still not changed to `const`

2019-12-04 23:22 UTC, divyanshu-rawat commented on src/Views/editor.js
> +            <CustomEditor/>
Looks good!

2019-12-04 23:52 UTC, divyanshu-rawat reviewed
I have added all general suggestion that will make code more red-able.
Let me know your thoughts on my feedback :).

2019-12-04 23:52 UTC, divyanshu-rawat commented on src/Components/customEditor/editor.css
> +#mainEditor {
what is the purpose of this css `id`, remove it if you are not making use of it.

2019-12-04 23:52 UTC, divyanshu-rawat commented on src/Components/toolbar/toolbar.js
> +    _closeModal = () => {
any specific reason for naming the functions starting with `_`, prefer normal camelCase approach as you did in other cases.

2019-12-04 23:52 UTC, divyanshu-rawat commented on src/Components/toolbar/toolbar.js
> +    _items = [
same here any reason for starting the name with `_`

2019-12-04 23:52 UTC, divyanshu-rawat commented on src/Components/toolbar/toolbar.js
> +                            if(this.state.fileCount === 0) {
for readability point of view, you can also declare fileCount above return, like this.

`const { fileCount } = this.state; `

 or 

` const { state: { fileCount }} = this;`

2019-12-04 23:52 UTC, divyanshu-rawat commented on src/Components/toolbar/toolbar.js
> +        return (
I think above `return` you can declare all **state variables** to make it more readable.
Something like this.

`const { fileCount, isModalOpen, files } = this.state; `

**or** 

`const { state: { fileCount, isModalOpen, files }} = this;`

2019-12-04 23:52 UTC, divyanshu-rawat commented on src/Components/toolbar/toolbar.js
> +        return (
It is totally upto you which way you prefer. :)

2019-12-04 23:52 UTC, divyanshu-rawat commented on src/Components/toolbar/toolbar.js
> +            <div>
you can also use `<Fragment />` if you want, it's totally upto you.

2019-12-04 23:52 UTC, divyanshu-rawat commented on src/Components/customEditor/customEditor.js
> +        this.setState({fileName: fileName, fileType: fileType})
I think you can also re-write this as.

`this.setState({ fileName, fileType });`

2019-12-08 20:59 UTC, divyanshu-rawat commented
@davidli3100 are you still working on it?

2019-12-08 21:00 UTC, davidli3100 commented
Yeah I am. A few more readability issues left

On Sun., Dec. 8, 2019, 3:59 p.m. Divyanshu Rawat, <notifications@github.com>
wrote:

> @davidli3100 <https://github.com/davidli3100> are you still working on it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JBossOutreach/react-online-editor/pull/1?email_source=notifications&email_token=AF5RNNLRVDJ2MHN3MRY4HILQXVN2PA5CNFSM4JUQZGTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGHJO3Q#issuecomment-562993006>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF5RNNPQLW7JG7BGNTCFYOTQXVN2PANCNFSM4JUQZGTA>
> .
>

2019-12-08 21:06 UTC, davidli3100 commented
Updated the suggested readability changes. Thanks for the feedback!

2019-12-08 21:54 UTC, divyanshu-rawat approved these changes
LGTM 👍

2019-12-08 22:09 UTC, davidli3100 commented
Cool! Let me know if there are any more React/JS based tasks left over,

2019-12-09 10:10 UTC, merged

2019-12-09 10:11 UTC, divyanshu-rawat commented
https://deploy-preview-1--react-online-editor.netlify.com/ looks good to me.